# Generated by Django 4.2.27 on 2026-01-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_remove_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='cashback_type',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cashback_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='has_cashback',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SharedExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=False)),
                ('is_payer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_participations', to='expenses.friend')),
                ('shared_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.sharedexpense')),
            ],
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_details', to='expenses.expense'),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.sharedexpenseparticipant')),
                ('shared_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.sharedexpense')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('friend__isnull', False)), fields=('shared_expense', 'friend'), name='unique_friend_per_shared_expense'),
        ),
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_user', True)), fields=('shared_expense', 'is_user'), name='unique_user_per_shared_expense'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('shared_expense', 'participant'), name='unique_share_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_share_amount'),
        ),
    ]
