# Generated by Django 4.2.27 on 2026-02-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0014_friend_sharedexpense_expense_cashback_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friends",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="friend",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
