# Generated by Django 4.2.27 on 2026-02-02 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0015_friend_user_alter_friend_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_image", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=100)),
                ("credit_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "available_limit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "billing_cycle_day",
                    models.PositiveIntegerField(
                        help_text="Day of month when bill generates (1-28)"
                    ),
                ),
                (
                    "due_date_days",
                    models.PositiveIntegerField(
                        default=20, help_text="Days after billing date to pay"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["bank_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_image",
                    models.CharField(
                        blank=True,
                        help_text="Icon image name for UI representation",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Account"),
                            ("current", "Current Account"),
                            ("wallet", "Digital Wallet"),
                            ("cash", "Cash in Hand"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_friend_per_user"
            ),
        ),
        migrations.AddField(
            model_name="paymentsource",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="credit_card",
            field=models.ForeignKey(
                blank=True,
                help_text="Credit card used for this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="expenses.creditcard",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account, wallet, or cash source used for this expense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="expenses.paymentsource",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentsource",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_payment_source_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditcard",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_credit_card_per_user"
            ),
        ),
    ]
