# Generated by Django 4.2.27 on 2026-02-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0018_add_settlement_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="payment_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account/wallet where money is transferred from/to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements",
                to="expenses.paymentsource",
            ),
        ),
    ]
