# Generated by Django 4.2.27 on 2026-02-19 06:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_alter_expense_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_to_credit_card',
            field=models.BooleanField(default=False, help_text='True if the expense has already been paid to the credit card.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
